opt/vyatta/share/perl5/Vyatta/Aggregate.pm
opt/vyatta/share/perl5/Vyatta/FWHelper.pm
opt/vyatta/share/perl5/Vyatta/NpfRuleset.pm
opt/vyatta/share/perl5/Vyatta/NPTv6Stats.pm
opt/vyatta/share/perl5/Vyatta/SessionStats.pm
opt/vyatta/share/perl5/Vyatta/Npf/GetPort.pm
opt/vyatta/share/perl5/Vyatta/Npf/GetPortTypeAndValue.pm
opt/vyatta/share/perl5/Vyatta/Npf/ValidateNpfRule.pm

opt/vyatta/share/perl5/Vyatta/Npf/Warning.pm

opt/vyatta/sbin/end-npf-interfaces
opt/vyatta/sbin/npf-get-nptv6-state
opt/vyatta/sbin/npf-get-state
opt/vyatta/sbin/npf-get-state-fw
opt/vyatta/sbin/npf-get-state-nat
opt/vyatta/sbin/npf-get-state-pbr
opt/vyatta/sbin/npf-get-state-zones
opt/vyatta/sbin/validate-fw-groups
opt/vyatta/sbin/validate-session-usage
opt/vyatta/sbin/vyatta-dp-npf.pl
opt/vyatta/sbin/vyatta-dp-npf-clear
opt/vyatta/sbin/vyatta-dp-npf-show-nat-trans
opt/vyatta/sbin/vyatta-dp-npf-show-nptv6
opt/vyatta/sbin/vyatta-dp-npf-show-rules
opt/vyatta/sbin/vyatta-dp-npf-snmptrap.pl
opt/vyatta/sbin/npf-show-logs

opt/vyatta/share/vyatta-op/functions/tech-support.d
