usr/share/configd/yang/vyatta-service-nat-cgnat-v1.yang

opt/vyatta/sbin/cgnat-configuration
opt/vyatta/sbin/cgnat-get-state
opt/vyatta/sbin/cgnat-get-subscriber-rpc
opt/vyatta/sbin/cgnat-get-public-rpc
opt/vyatta/sbin/cgnat-get-sessions-rpc
opt/vyatta/sbin/cgnat-clear-sessions-rpc
opt/vyatta/sbin/cgnat-clear-session-stats-rpc
opt/vyatta/sbin/cgnat-clear-subs-stats-rpc
opt/vyatta/sbin/cgnat-clear-policy-stats-rpc
opt/vyatta/sbin/cgnat-clear-errors-rpc

etc/systemd/system/td-agent-bit.service.d/10-disable
lib/systemd/system/td-agent-bit@.service
