#!/bin/bash

if [ "$COMMIT_ACTION" != "DELETE" ]
then
    vyatta-dp-npf.pl --variant=route --cmd=update --group="$1"
fi
vyatta-dp-npf.pl --cmd=commit
vyatta-dp-npf-snmptrap.pl --level="policy route pbr"
