#!/bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#

if [ ${COMMIT_ACTION} = 'DELETE' ] ;
then
    # detach from interface(s) before deleting group
    npf-session-limit.pl --cmd="assign" --type="group" --name="$1"

    vyatta-dp-npf.pl --variant=session-limiter --cmd="delete-group" --group="$1"
    vyatta-dp-npf.pl --cmd=commit
else
    vyatta-dp-npf.pl --variant=session-limiter --cmd="update" --group="$1"
    vyatta-dp-npf.pl --cmd=commit

    # attach/detach to/from interface(s)
    npf-session-limit.pl --cmd="assign" --type="group" --name="$1"
fi
