#!/bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#

if [ "$COMMIT_ACTION" != "DELETE" ]
then
    vyatta-dp-npf.pl --variant=firewall --cmd=update --group="$1"
fi
