#!/bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#

if [ "$COMMIT_ACTION" != "DELETE" ]
then
    vyatta-dp-npf.pl --variant=route --cmd=update --group="$1"
fi
vyatta-dp-npf.pl --cmd=commit
vyatta-dp-npf-snmptrap.pl --level="policy route pbr"
