#!/bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#

INTF=$1

if [ "$INTF" != "lo" ]
then
	>2& echo "Failed: Firewalls can only be assigned to 'lo'"
	exit 1
fi
