#!/bin/dash

#
# Copyright (c) 2018-2019, AT&T Intellectual Property. All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#

exec /opt/vyatta/bin/vplsh -l -c "npf-op state all: snat dnat nat64"
