#!/bin/bash
#
# Copyright (c) 2018-2019, AT&T Intellectual Property.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#

journalctl -a -o short-precise --no-hostname -u vyatta-dataplane | egrep "$1"
