#!/bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#

declare -A sysctlval=(["disable"]="0" ["enable"]="1")

sysctl -wq net.ipv4.tcp_syncookies=${sysctlval[$1]}
