#!/bin/bash
#
# Copyright (c) 2019, AT&T Intellectual Property.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#

declare -A sysctlval=(["enable"]="0" ["disable"]="1")

sysctl -wq "net.ipv4.icmp_echo_ignore_$1=${sysctlval[$2]}"
